### ISSUE TITLE
Incorrect SDK version numbers

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-Android#1121]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Android/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Android/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Android SDK](https://github.com/parse-community/Parse-SDK-Android/releases). 

### Issue Description
It seems that versions and builds for all packages are `1`.

https://github.com/parse-community/Parse-SDK-Android/blob/dd9a9e6465591fc9b94a259551e5d338a4c150ea/parse/build.gradle#L11-L12

https://github.com/parse-community/Parse-SDK-Android/blob/dd9a9e6465591fc9b94a259551e5d338a4c150ea/facebook/build.gradle#L11-L12
#1068 
### Steps to reproduce
n/a

### Solution
This should probably be set according to the release version / build.

### Alternative
Keep it as it is, the version to download is defined in jitpack anyway, but parse server will not store the correct parse version.
Related issue: https://github.com/parse-community/Parse-SDK-Android/issues/1068

### TODO
- [ ] Bump version in release automation

**Comment by L3K0V** [comment]
@mtrezza I found https://github.com/KengoTODA/gradle-semantic-release-plugin which can be integrated here with the release CI configuration. I will check if is possible. Later I can check once we have the correct versions #1068 I will open PR these days.

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [2.0.3](https://github.com/parse-community/Parse-SDK-Android/releases/tag/2.0.3)
