### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dplewis** [parse-community/Parse-SDK-Android#879]
With Hacktoberfest approaching I thought I would setup a roadmap of missing / undocumented functionality. 

If you would like to contribute, please feel free to open a PR. We'll gladly look it over.

- [ ] [and Query](https://github.com/parse-community/Parse-SDK-JS/pull/367)
- [ ] [nor Query](https://github.com/parse-community/parse-server/pull/4768)
- [ ] [containedBy Query](https://github.com/parse-community/parse-server/pull/4766)
- [ ] [sort option for near Queries](https://github.com/parse-community/parse-server/pull/4825)
- [ ] [query IncludeAll / include('*')](https://github.com/parse-community/parse-server/pull/4838)
- [ ] [fetch with include](https://github.com/parse-community/parse-server/pull/4845)
